# ================================================
# TRAEFIK CONFIGURATION
# ================================================

# Global Configuration
global:
  checkNewVersion: true

api:
  dashboard: true

providers:
  providersThrottleDuration: 2s
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: external
    watch: true
  file:
    directory: "/etc/traefik/custom"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    http3:
      advertisedPort: 443
    address: ":443"
    http:
      tls:
        options: modern-tls

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      keyType: "RSA4096"
      storage: /letsencrypt/acme.json
      tlsChallenge: true
  cloudflare:
    acme:
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"  # TESTING ONLY
      email: your-email@yourdomain.com
      storage: /letsencrypt/acme.json  # Simpan di volume persisten
      keyType: EC_P256               # Gunakan ECC untuk performa & keamanan
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 60
          disableChecks: true
          requireAllRNS: true
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  zerossl:
    acme:
      caServer: https://acme.zerossl.com/v2/DV90
      email: your-email@example.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 60
          disableChecks: true
          requireAllRNS: true
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

tls:
  options:
    modern-tls:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true

log:
  level: debug  # for error level logging
  filepath: "/logs/error.log"
  maxSize: 10
  maxAge: 28
  maxBackups: 5

accessLog:
  filePath: "/logs/access.log"
  format: json
  filters:
    statusCodes:
      - "200-299" # log successful http requests
      - "400-599" # log failed http requests
  bufferingSize: 1000 # Buffer untuk performa
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        Authorization: drop
        Cookie: drop

# Metrics (Optional - untuk monitoring)
# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addRoutersLabels: true
#     addServicesLabels: true
#     buckets:
#       - 0.1
#       - 0.3
#       - 1.2
#       - 5.0

# Tracing (Optional)
# tracing:
#   jaeger:
#     samplingServerURL: http://jaeger:5778/sampling
#     localAgentHostPort: jaeger:6831
